spring.application.name=pagos-proyecto
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/pagos_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Ver SQL formateado en consola
spring.jpa.properties.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ver logs de Spring Security (útil para debug)
logging.level.org.springframework.security=DEBUG

# Configuración temporal de usuario para el microservicio de Pagos
spring.security.user.name=admin_pagos
spring.security.user.password=Pagos2026!
